use app::error::Error;

mod app;
mod client;

#[tokio::main]
async fn main() -> Result<(), Error>{
    

    Ok(())
}
